name: nixage
version: 0.0.0

default-extensions:
  - ApplicativeDo
  - DeriveGeneric
  - FlexibleContexts
  - FlexibleInstances
  - GeneralizedNewtypeDeriving
  - LambdaCase
  - NamedFieldPuns
  - NoImplicitPrelude
  - OverloadedStrings
  - PatternSynonyms
  - RankNTypes
  - ScopedTypeVariables
  - StandaloneDeriving
  - TemplateHaskell
  - TupleSections
  - TypeApplications
  - TypeFamilies

library:
  source-dirs: lib

  dependencies:
    - base
    - universum

    - aeson
    - aeson-options
    - containers
    - text

executables:
  nixage:
    source-dirs: cli
    main: Main.hs

    dependencies:
      - base
      - universum

      - nixage

      - optparse-applicative
      - process
      - temporary
      - yaml

    ghc-options:
      - -threaded
